#importing dataset
app_dataset = read.csv('AppleStore.csv')

str(app_dataset)
colSums(is.na(app_dataset)) #there are no NA values.

free_apps <- subset(app_dataset, app_dataset$price == 0)
View(free_apps)
a= nrow(free_apps)
cat('The number of free apps are ',a)
paid_apps <- subset(app_dataset, app_dataset$price !=  0)
View(paid_apps)
b = nrow(paid_apps)
cat('The number of paid apps are ',b)
max_price = max(paid_apps$price)
min_price = min(paid_apps$price)
cat('The most expensive app is of USD ',max_price)
cat('The most expensive app is of USD ',min_price)
c <- subset(paid_apps, paid_apps$price == max_price)
d <- subset(paid_apps, paid_apps$price == min_price)
paste('The most expensive app is ', unique(c$track_name))
paste('The number of least USD apps are', nrow(d), 'and is of USD',min_price)
paste('The least expensive app is ', unique(d$track_name), '\n')
max_lang <- max(app_dataset$lang.num)
e <- subset(app_dataset, (app_dataset$lang.num)== max_lang)
paste('The app that is available with max languages is ', unique(e$track_name), 'and is available in',max_lang, 'languages')
table(app_dataset$prime_genre)
library(ggplot2)
qplot(app_dataset$prime_genre)+ theme(axis.text.x = element_text(angle = 90, hjust = 1)) + ggtitle('maximum genre apps plot')
